events {
    worker_connections 1024;
}

http {
    access_log /dev/stdout;
    error_log /dev/stdout info;

    server {
        listen 10000;
        
        location / {
            proxy_pass http://VM_B_IP:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
} 